#!/usr/bin/env bash
set -ex

export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required

export MALLOC_TRIM_THRESHOLD_=65536

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

python -m exaspim_flatfield_correction.pipeline --config "/data/config.json" 

echo "Done!"
