#!/usr/bin/env bash
set -ex

export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required

export MALLOC_TRIM_THRESHOLD_=65536

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# Check if eighth argument is 1
BINNED_FLAG=""
if [ "$8" == "1" ]; then
  BINNED_FLAG="--is-binned"
fi

python -u -m exaspim_flatfield_correction.pipeline.run_pipeline \
--zarr "$1" \
--output "$2" \
--res "$3" \
--method "$4" \
--flatfield-path "$5" \
--num-workers "$6" \
--mask-dir "$7" \
--n-levels 7 \
--results-dir "/results" \
--overwrite \
$BINNED_FLAG

echo "Done!"
