#!/usr/bin/env bash
set -ex

export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
pip install .[basicpy]
python -u -m exaspim_flatfield_correction.pipeline.run_pipeline \
--zarr "$1" \
--output "$2" \
--res "$3" \
--method "$4" \
--flatfield-path "$5" \
--num-workers "$6" \
--mask-dir "$7" \
--n-levels 7 \
--results-dir "/results" \
--overwrite

echo "Done!"
