#!/usr/bin/env bash
set -ex

export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required

export MALLOC_TRIM_THRESHOLD_=0

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

python -u run_pipeline.py \
--zarr "$1" \
--output "$2" \
--res "$3" \
--method "$4" \
--overwrite \
--flatfield-path "$5" \
--num-workers "$6" \
--mask-dir "/data/masks" \
--n-levels 7

echo "Done!"
